version: "3.9"

services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=phuoclong
      - MONGO_INITDB_ROOT_PASSWORD=516489
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/cert.pem:/etc/ssl/cert.pem
  #     - ./nginx/key.pem:/etc/ssl/key.pem
  #     - ./nginx/tcplong.xyz:/etc/nginx/conf.d/tcplong.conf
    
  app:
    build: ./
    container_name: server
    restart: always
    ports: 
      - 4004:4004
    volumes:
      - ./env-docker/.env:/app/src/.env
    depends_on:
      - mongodb
      - redis

