version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongo0
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=phuoclong
      - MONGO_INITDB_ROOT_PASSWORD=516489
  redis:
    image: redis:latest
    container_name: mongo0
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  app:
    build: ./
    ports: 
      - 4004:4004
    volumes:
      - ./.env:/app/src
    depends_on:
      - mongodb
      - redis

    
